### ISSUE TITLE
Scrolling doesn't work inside terminal

### ISSUE THREAD

**Issue by avinal** [sharpvik/sharpvik.github.io#4]
The terminal looks awesome. Kudos for that. I can't say if this was intended behavior, but scrolling doesn't seem to be working in the terminal.

**Comment by sharpvik** [comment]
Hey @avinal, yes, disabled scrolling is part of the "old terminal feel" that I wanted to give. It is not a bug.

**Comment by avinal** [comment]
Thanks, I got it working for me.
